In [1]:
from load_campus_pose import *
from gt_campus import *
import numpy as np
import pickle
import os

# Voxel pose
## Generate 2D human centers poses 

In [2]:
vx_data=voxel_campus()
joints='joints_2d'

In [8]:
dic_frame={}
for frame in range (704,1999):
    dic_cam={}
    for cam in range (3) :
        cdm_frame=[]
        for j in vx_data.get_data_campus(frame,cam,joints) :
          #  print('joints = \n',j)
            cdm=(j[2]+j[3])/2
            cdm_frame = np.append(cdm_frame , cdm)
        if len(cdm_frame) != 0 : 
            cdm_frame=cdm_frame.reshape(len(cdm_frame)//2, 2)
        dic_cam.update({'camera_'+str(cam) :  cdm_frame})
    dic_frame.update({'image_'+str(frame)  : dic_cam})


In [9]:
dic_frame

{'image_704': {'camera_0': array([[346.53809516, 130.57029035],
         [285.00512448, 129.44381664],
         [183.33474792, 122.28223188]]),
  'camera_1': array([[198.52145921, 110.3389155 ],
         [221.50284195, 112.04866311],
         [ 52.31385498, 124.28657887]]),
  'camera_2': array([[291.31707811, 125.59425032],
         [199.02605649, 112.71530095],
         [283.22353229,  99.43548946]])},
 'image_705': {'camera_0': array([[346.53809516, 130.57029035],
         [285.00512448, 129.44381664],
         [183.83120711, 122.31641415]]),
  'camera_1': array([[198.52145921, 110.3389155 ],
         [221.50284195, 112.04866311],
         [ 52.81141318, 124.24238287]]),
  'camera_2': array([[291.31707811, 125.59425032],
         [199.02605649, 112.71530095],
         [283.45337135,  99.52685345]])},
 'image_706': {'camera_0': array([[345.56405247, 130.78565561],
         [285.00512448, 129.44381664],
         [184.32769106, 122.35035634]]),
  'camera_1': array([[198.53322089, 110.56

In [10]:
# save
destination=os.path.abspath('../../data/Campus/voxel_2d_human_centers.pkl')
a_file = open(destination, "wb")
pickle.dump(dic_frame, a_file)
a_file.close()

## Generate 3D human centers poses 

In [11]:
joints_3d='joints_3d'
dic_frame_3d={}
for frame in range (704,1999):
    cdm_frame=[]
    for j in vx_data.get_data_campus(frame,cam,joints_3d) :
          #  print('joints = \n',j)
        cdm=(j[2]+j[3])/2
        cdm_frame = np.append(cdm_frame , cdm)
    if len(cdm_frame) != 0 : 
        cdm_frame=cdm_frame.reshape(len(cdm_frame)//3, 3)    
    dic_frame_3d.update({'image_'+str(frame) : cdm_frame})


In [12]:
dic_frame_3d

{'image_704': array([[5302.91643858, 4307.188706  ,  989.86675142],
        [3874.04802415, 3875.83181468, 1073.7736668 ],
        [1799.89765807, 7310.64019328,  990.63135179]]),
 'image_705': array([[5302.91643858, 4307.188706  ,  989.86675142],
        [3874.04802415, 3875.83181468, 1073.7736668 ],
        [1813.50782937, 7304.45749678,  989.92487938]]),
 'image_706': array([[5282.23214677, 4308.27034636,  985.35811094],
        [3874.04802415, 3875.83181468, 1073.7736668 ],
        [1827.46534939, 7298.70373278,  989.20272273]]),
 'image_707': array([[5249.35016341, 4337.84005221,  959.79487104],
        [3874.04802415, 3875.83181468, 1073.7736668 ],
        [1829.0128002 , 7279.92765819,  968.57552772]]),
 'image_708': array([[5204.7954258 , 4343.11573307,  988.93715482],
        [3874.04802415, 3875.83181468, 1073.7736668 ],
        [1828.70183299, 7243.06593095,  970.15051638]]),
 'image_709': array([[5173.13775272, 4345.4529376 ,  990.40328576],
        [3874.04802415, 3875.831

In [13]:
# save
destination=os.path.abspath('../../data/Campus/voxel_3d_human_centers.pkl')
a_file = open(destination, "wb")
pickle.dump(dic_frame_3d, a_file)
a_file.close()

In [14]:

file=os.path.abspath('../../data/Campus/voxel_3d_human_centers.pkl')
a_file = open(file, "rb")
output = pickle.load(a_file)
a_file.close()

In [15]:
output['image_1169']

array([[3639.53808649, 3450.05856202, 1002.17334822]])

# Ground Truth

In [16]:
gt_data=gt()

In [17]:
frame=2
actor=1
camera=1
gt_data.get_human_center(frame,actor,camera)

array([346.5, 131. ])

In [18]:
dic_frame={}
for frame in range(704,1999):
    dic_cam={}
    for cam in range(1,4) :
        cdm_frame=[]
        for actor in range (1,4):
            cdm_cam=gt_data.get_human_center(frame-703,actor,cam)
            if cdm_cam.all() != 0.:
                cdm_frame = np.append(cdm_frame , cdm_cam)
        if len(cdm_frame) != 0 : 
            cdm_frame=cdm_frame.reshape(len(cdm_frame)//2, 2)
        dic_cam.update({'camera_'+str(cam-1) : cdm_frame})
    dic_frame.update({'image_'+str(frame)  : dic_cam})

In [19]:
destination=os.path.abspath('../../data/Campus/GT_2d_human_centers.pkl')
a_file = open(destination, "wb")
pickle.dump(dic_frame, a_file)
a_file.close()

In [20]:
a_file = open(destination, "rb")
output = pickle.load(a_file)
a_file.close()
output['image_1169']

{'camera_0': array([[278. , 135.5]]),
 'camera_1': array([[240., 116.]]),
 'camera_2': array([[166.2684 , 118.25453]])}

## 3D

In [22]:
dic_frame_3d_GT={}
for frame in range(704,1999):
    dic_cam={}
    cdm_frame=[]
    for actor in range (1,4):
            cdm_cam=gt_data.get_human_center3D(frame-703,actor)*1e3
            if cdm_cam.all() != 0.:
                cdm_frame = np.append(cdm_frame , cdm_cam)
    if len(cdm_frame) != 0 : 
            cdm_frame=cdm_frame.reshape(len(cdm_frame)//3, 3)
    dic_frame_3d_GT.update({'image_'+str(frame)  : cdm_frame})


In [23]:
dic_frame_3d_GT['image_1159']

array([[3729.21185, 3730.0547 , 1006.28125]])

In [24]:
# save
destination=os.path.abspath('../../data/Campus/GT_3d_human_centers.pkl')
a_file = open(destination, "wb")
pickle.dump(dic_frame_3d_GT, a_file)
a_file.close()